// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT4hKvtaq31vUKs2Fh2ENeHw5HYZxn4_4',
    appId: '1:928162553988:web:cdf3daf259fb5717de62d1',
    messagingSenderId: '928162553988',
    projectId: 'expanse-97da0',
    authDomain: 'expanse-97da0.firebaseapp.com',
    storageBucket: 'expanse-97da0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5Oqx6Z7sQDejl1HFNXvx2jgjZUOAY0h4',
    appId: '1:928162553988:android:36d58ecf4f7c66edde62d1',
    messagingSenderId: '928162553988',
    projectId: 'expanse-97da0',
    storageBucket: 'expanse-97da0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5lYrmGbfKt8BmtU10w3B5UuQoqsr5-wg',
    appId: '1:928162553988:ios:e8663f24d130a0f3de62d1',
    messagingSenderId: '928162553988',
    projectId: 'expanse-97da0',
    storageBucket: 'expanse-97da0.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5lYrmGbfKt8BmtU10w3B5UuQoqsr5-wg',
    appId: '1:928162553988:ios:ae6d5d109cd36c63de62d1',
    messagingSenderId: '928162553988',
    projectId: 'expanse-97da0',
    storageBucket: 'expanse-97da0.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
